stages:
  - build
  - test

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

build_job:
  stage: build
  image: maven:3.8.6-eclipse-temurin-21 # Utiliser Java 21
  script:
    - cd TourGuide
    - chmod +x mvnw
    - ./mvnw compile --batch-mode --errors --fail-at-end --show-version -- \
      -DinstallAtEnd=true \
      -DdeployAtEnd=true \
      -Dhttps.protocols=TLSv1.2 \
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository \
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN \
      -Dorg.slf4j.simpleLogger.showDateTime=true \
      -Djava.awt.headless=true





test_job:
  stage: test
  image: maven:3.8.6-eclipse-temurin-21  # Utiliser Java 21
  script:
    - cd TourGuide
    - chmod +x mvnw
    - ./mvnw test --batch-mode --errors --fail-at-end --show-version -- \
      -DinstallAtEnd=true \
      -DdeployAtEnd=true \
      -Dhttps.protocols=TLSv1.2 \
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository \
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN \
      -Dorg.slf4j.simpleLogger.showDateTime=true \
      -Djava.awt.headless=true



